<?php
pll_register_string( 'search', 'search', 'cyan-dm' );
pll_register_string( 'sorry , no posts found', 'sorry , no posts found', 'cyan-dm' );
pll_register_string( 'Blogs', 'Blogs', 'cyan-dm' );
pll_register_string( 'profile', 'profile', 'cyan-dm' );
pll_register_string( 'Contact Iprefab', 'Contact Iprefab', 'cyan-dm' );
pll_register_string( 'Follow Us', 'Follow Us', 'cyan-dm' );
pll_register_string( 'oops something went wrong', 'oops something went wrong', 'cyan-dm' );
pll_register_string( 'back to homepage', 'back to homepage', 'cyan-dm' );
pll_register_string( 'suppliers', 'suppliers', 'cyan-dm' );
pll_register_string( 'All Suppliers', 'All Suppliers', 'cyan-dm' );
pll_register_string( 'contact us', 'contact us', 'cyan-dm' );
pll_register_string( 'your name', 'your name', 'cyan-dm' );
pll_register_string( 'your email', 'your email', 'cyan-dm' );
pll_register_string( 'Your Message', 'Your Message', 'cyan-dm' );
pll_register_string( 'about us', 'about us', 'cyan-dm' );
pll_register_string( 'suppliers', 'suppliers', 'cyan-dm' );
pll_register_string( 'houses', 'houses', 'cyan-dm' );
pll_register_string( 'visit website', 'visit website', 'cyan-dm' );
pll_register_string( 'call company', 'call company', 'cyan-dm' );
pll_register_string( 'about company', 'about company', 'cyan-dm' );
pll_register_string( 'call back request', 'call back request', 'cyan-dm' );
pll_register_string( 'houses in IPREFAB', 'houses in IPREFAB', 'cyan-dm' );
pll_register_string( 'Author', 'Author', 'cyan-dm' );
pll_register_string( 'Date', 'Date', 'cyan-dm' );
pll_register_string( 'You might also like', 'You might also like', 'cyan-dm' );
pll_register_string( 'call', 'call', 'cyan-dm' );
pll_register_string( 'visit advertise', 'visit advertise', 'cyan-dm' );
pll_register_string( 'neighborhood', 'neighborhood', 'cyan-dm' );
pll_register_string( 'building right', 'building right', 'cyan-dm' );
pll_register_string( 'contact name', 'contact name', 'cyan-dm' );
pll_register_string( 'contact number', 'contact number', 'cyan-dm' );
pll_register_string( 'fee', 'fee', 'cyan-dm' );
pll_register_string( 'city', 'city', 'cyan-dm' );
pll_register_string( 'neighborhood', 'neighborhood', 'cyan-dm' );
pll_register_string( 'permit type', 'permit type', 'cyan-dm' );
pll_register_string( 'permit size', 'permit size', 'cyan-dm' );
pll_register_string( 'total area', 'total area', 'cyan-dm' );
pll_register_string( 'houses that are suitable for the land', 'houses that are suitable for the land', 'cyan-dm' );
pll_register_string( 'view all', 'view all', 'cyan-dm' );
pll_register_string( 'origin of company', 'origin of company', 'cyan-dm' );
pll_register_string( 'house area', 'house area', 'cyan-dm' );
pll_register_string( 'rooms', 'rooms', 'cyan-dm' );
pll_register_string( 'floors', 'floors', 'cyan-dm' );
pll_register_string( 'House Info', 'House Info', 'cyan-dm' );
pll_register_string( 'material', 'material', 'cyan-dm' );
pll_register_string( 'balcony', 'balcony', 'cyan-dm' );
pll_register_string( 'garage', 'garage', 'cyan-dm' );
pll_register_string( 'kitchen appliances', 'kitchen appliances', 'cyan-dm' );
pll_register_string( 'bathroom appliances', 'bathroom appliances', 'cyan-dm' );
pll_register_string( 'celling style', 'celling style', 'cyan-dm' );
pll_register_string( 'Facade / Material', 'Facade / Material', 'cyan-dm' );
pll_register_string( 'garage (open or close)', 'garage (open or close)', 'cyan-dm' );
pll_register_string( 'land details', 'land details', 'cyan-dm' );
pll_register_string( 'company verification type', 'company verification type', 'cyan-dm' );
pll_register_string( 'sauna', 'sauna', 'cyan-dm' );
pll_register_string( 'Primary', 'Primary', 'cyan-dm' );
pll_register_string( 'add to calender', 'add to calender', 'cyan-dm' );
pll_register_string( 'call back request', 'call back request', 'cyan-dm' );
pll_register_string( 'Details', 'Details', 'cyan-dm' );
pll_register_string( 'Designed to be open and spacious, the impressive hillside house sits diagonally to the slope, which
					creates an architecturally individual and fascinating look for the home. The entrance to the home is on
					the side of the upper slope.', 'Designed to be open and spacious, the impressive hillside house sits diagonally to the slope, which
					creates an architecturally individual and fascinating look for the home. The entrance to the home is on
					the side of the upper slope.', 'cyan-dm', true );
pll_register_string( 'I accept have a land for this house', 'I accept have a land for this house', 'cyan-dm' );
pll_register_string( 'Order a bank request', 'Order a bank request', 'cyan-dm' );

pll_register_string( 'Description', 'Description', 'cyan-dm' );
pll_register_string( 'visit builder', 'visit builder', 'cyan-dm' );
pll_register_string( 'The address of the house presentation', 'The address of the house presentation', 'cyan-dm' );
pll_register_string( 'Guidance', 'Guidance', 'cyan-dm' );
pll_register_string( 'show driving directions', 'show driving directions', 'cyan-dm' );
pll_register_string( 'collection', 'collection', 'cyan-dm' );
pll_register_string( 'Full Name', 'Full Name', 'cyan-dm' );
pll_register_string( 'Email', 'Email', 'cyan-dm' );
pll_register_string( 'Phone', 'Phone', 'cyan-dm' );
pll_register_string( 'Price', 'Price', 'cyan-dm' );
pll_register_string( 'City', 'City', 'cyan-dm' );
pll_register_string( 'Personal Info', 'Personal Info', 'cyan-dm' );
pll_register_string( 'Get Advice For', 'Get Advice For', 'cyan-dm' );
pll_register_string( 'house', 'house', 'cyan-dm' );
pll_register_string( 'house + land', 'house + land', 'cyan-dm' );
pll_register_string( 'you looking for ... ', 'you looking for ... ', 'cyan-dm' );
pll_register_string( 'house type', 'house type', 'cyan-dm' );
pll_register_string( 'Homepage', 'Homepage', 'cyan-dm' );
pll_register_string( 'area min', 'area min', 'cyan-dm' );
pll_register_string( 'let’s find a house', 'let’s find a house', 'cyan-dm' );
pll_register_string( 'Frequently Asked Questions', 'Frequently Asked Questions', 'cyan-dm' );
pll_register_string( 'sorry, we have not found anything!', 'sorry, we have not found anything!', 'cyan-dm' );
pll_register_string( 'Ask Builder', 'Ask Builder', 'cyan-dm' );
pll_register_string( 'brochure', 'brochure', 'cyan-dm' );
pll_register_string( 'Filters', 'Filters', 'cyan-dm' );
?>